version: '3.7'

services:
  api:
    build:
      context: .
      target: development
    command:
      - /bin/sh
      - -c
      - |
        npm run start:dev
        npm run prisma:generate:watch
    restart: unless-stopped
    networks:
      - backend
    env_file:
      - .env
    volumes:
      - ./:/api
      - /api/node_modules
      - /api/dist
    ports:
      - "3001:3001"
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - backend
    env_file:
      - .env
    volumes:
      - redis_data:/data

  postgres:
    image: postgis/postgis:14-3.3-alpine
    platform: linux/x86_64
    restart: unless-stopped
    networks:
      - backend
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  backend:

volumes:
  postgres_data:
  redis_data:
